Django/board/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # Create
    # articles/new/
    path('new/', views.new, name='new'),
    # articles/create/
    path('create/', views.create, name='create'),

    # Read
    # articles/
    path('', views.list, name='list'),
    # articles/1/
    path('<int:pk>/', views.detail, name='detail'),

    # Update
    # articles/1/edit/
    path('<int:pk>/edit/', views.edit, name='edit'),
    # articles/1/update/
    path('<int:pk>/update/', views.update, name='update'),

    # Delete
    # articles/1/delete/
    path('<int:pk>/delete/', views.delete, name='delete'),
]

Django/board/board/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

Django/board/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'({self.pk}): {self.title}'

Django/board/articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Article

"""
1. 글 작성 버튼을 누르면(/aritcles/new)
2. form 제공
3. form 제출시 (/articles/create)
4. 글 작성(db save)
5. detail 페이지로 이동 / list 이동
"""

# Create
def new(request):
    return render(request, 'articles/new.html')


def create(request):
    article = Article()
    article.title = request.POST['title']
    article.content = request.POST['content']
    article.save()

    # 현재 요청보낸 브라우저의 url을 /articles/3/로 바꿔주세요
    return redirect('articles:detail', article.pk)


# Read
def list(request):
    # id 오름차순이 기본값
    # articles = Article.objects.all()

    # id 내림차순 (python)
    # articles = Article.objects.all()[::-1]

    # id 내림차순 (ORM)
    # articles = Article.objects.order_by('-pk')

    # updated_at 내림차순
    articles = Article.objects.order_by('-updated_at')
    context = {'articles': articles, }
    return render(request, 'articles/list.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article, }
    return render(request, 'articles/detail.html', context)


# Update
def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article, }
    return render(request, 'articles/edit.html', context)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST['title']
    article.content = request.POST['content']
    article.save()
    return redirect('articles:detail', article.pk)


# Delete
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:list')
    elif request.method == 'GET':
        return redirect('articles:detail', article.pk)

Django/board/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ article.title }}</h1>

<p>
  {{ article.content | linebreaksbr }}
</p>

<div>
  <a href="{% url 'articles:edit' article.pk %}">
    <button>수정</button>
  </a>
</div>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <button onclick="return confirm('지울래?')">삭제</button>
</form>

{% endblock content %}

Django/board/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit Article</h1>

<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <div>
    제목: <input type="text" name="title" value="{{ article.title }}">
  </div>
  <div>
    내용: <textarea name="content" cols="30" rows="10">{{ article.content }}</textarea>
  </div>
  <div>
    <button>글 작성</button>
  </div>
</form>
{% endblock content %}

Django/board/articles/templates/articles/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Article List</h1>

<ul>
  {% for article in articles %}
  <li>
    <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
  </li>
  {% endfor %}
</ul>


{% endblock content %}

Django/board/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
<h1>New Article</h1>

<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  
  <div>
    제목: <input type="text" name="title">
  </div>
  <div>
    내용: <textarea name="content" cols="30" rows="10"></textarea>
  </div>
  <div>
    <button>글 작성</button>
  </div>
</form>
{% endblock content %}

Django/board/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <nav>
    <ul>
      <li>
        <a href="{% url 'articles:list' %}">Home</a>
      </li>
      <li>
        <a href="{% url 'articles:new' %}">New Article</a>
      </li>
    </ul>
  </nav>

  <div class="container">
    {% block content %}{% endblock content %}
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>