Django/basic_tv/basic_tv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # mysite app에 관련된 내용
    path('mysite/', include('mysite.urls')),
    path('pages/', include('pages.urls')),
    path('', include('galaxy.urls')),
]

Django/basic_tv/galaxy/urls.py
from django.urls import path
from . import views

app_name = 'galaxy'

urlpatterns = [
    # /ping/
    path('ping/', views.ping, name='ping'),
    # /pong/
    path('pong/', views.pong, name='pong'),
    path('pingpong/', views.pingpong, name='pingpong'),
]

Django/basic_tv/mysite/urls.py
# urls.py 를 생성 => include 할 경우, 꼭 urlapatterns = [] 를 작성하자.

from django.urls import path
from . import views

app_name = 'mysite'

urlpatterns = [
    # /mysite/
    path('', views.home),
    # /mysite/lunch/
    path('lunch/', views.lunch, name='lunch'),
    # /mysite/lotto/
    path('lotto/', views.lotto, name='lotto'),
    # /mysite/greeting/<var>/ <= Variable Routing
    path('greeting/<str:name>/', views.greeting)
]

Django/basic_tv/pages/urls.py
# pages.urls.py

from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    # /pages/dinner/chicken/6/
    path('dinner/<str:menu>/<int:count>/', views.dinner),
    # /pages/check/
    path('check/', views.check, name='lotto')
]

Django/basic_tv/galaxy/views.py
from django.shortcuts import render


def ping(request):
    return render(request, 'galaxy/ping.html')


def pong(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
    elif request.method == 'GET':
        username = request.GET['username']
        password = request.GET['password']

    context = {
        'username': username,
        'password': password,
    }
    return render(request, 'galaxy/pong.html', context)


# browser 에서 POST 요청 보내는 방법 => <form method="POST">
def pingpong(request):
    if request.method == 'GET':
        return render(request, 'galaxy/form.html')

    elif request.method == 'POST':

        c = int(request.POST['temperature'])
        f = c * 1.8 + 32

        context = { 'f': f, }
        return render(request, 'galaxy/result.html', context)

Django/basic_tv/mysite/views.py
from django.shortcuts import render  # => HTML 을 응답으로 주는 함수
from django.http import HttpResponse # => 그냥 데이터를 응답으로 주는 함수
import random


def home(request):
    # HTML 파일은 기본적으로 INSTALLED_APPS > templates 에서 찾는다!
    return render(request, 'mysite/home.html')


def lunch(request):
    # menus 중 랜덤한 하나의 메뉴를 보여주자!
    menus = ['설렁탕', '곱창', '회', '똠양꿍', ]
    menu = random.choice(menus)
    context = {
        'menu': menu,
    }
    return render(request, 'mysite/lunch.html', context)


def lotto(request):
    lucky_numbers = random.sample(range(1, 46), 6)
    context = {
        'lucky_numbers': lucky_numbers,
    }
    return render(request, 'mysite/lotto.html', context)


def greeting(request, name):
    context = {
        'name': name.capitalize(),
    }
    return render(request, 'mysite/greeting.html', context)

Django/basic_tv/pages/views.py
import re
from django.shortcuts import render


def dinner(request, menu, count):
    context = {
        'menu': menu,
        'count': count,
    }
    return render(request, 'pages/dinner.html', context)


def check(request):
    return render(request, 'pages/home.html')

Django/basic_tv/galaxy/templates/galaxy/form.html
{% extends 'base.html' %}

{% block content %}
<h1>섭씨</h1>

<form action="" method="POST">
  {% csrf_token %}
  <label for="f-temp">섭씨: </label>
  <input type="text" id="f-temp" name="temperature">

  <button>변환!</button>
</form>
{% endblock content %}

Django/basic_tv/galaxy/templates/galaxy/ping.html
{% extends 'base.html' %}

{% block content %}
<h1>Ping</h1>

<form action="{% url 'galaxy:pong' %}" method="POST">
  {% csrf_token %}
  <div>
    <label for="username">Username: </label>
    <input type="text" id="username" name="username">
  </div>
  <div>
    <label for="password">Password: </label>
    <input type="password" id="password" name="password">
  </div>
  <div>
    <input type="submit" value="로그인">
  </div>
</form>

{% endblock content %}

Django/basic_tv/galaxy/templates/galaxy/pong.html
{% extends 'base.html' %}

{% block content %}
<h1>Pong</h1>
<p>
  사용자: {{ username|upper }}
</p>
<p>
  비밀번호: {{ password }}
</p>
{% endblock content %}

Django/basic_tv/galaxy/templates/galaxy/result.html
{% extends 'base.html' %}

{% block content %}
<h1>화씨</h1>
<h2>
  {{ f }}
</h2>
{% endblock content %}

Django/basic_tv/mysite/templates/mysite/greeting.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ name }}님, 반갑습니다!</h1>

{% endblock content %}

Django/basic_tv/mysite/templates/mysite/home.html
{% extends 'base.html' %}

{% block content %}

<h1>This is MYSITE/HOME</h1>

{% endblock %}

Django/basic_tv/mysite/templates/mysite/lotto.html
{% extends 'base.html' %}

{% block content %}
<h1>Your Lucky Numbers</h1>

{% comment %} 
  {{ }} => print

  {% %} => else
{% endcomment %}

<ul>
  {% for number in lucky_numbers %}
    <li>{{ number }}</li>
  {% endfor %}
</ul>
{% endblock content %}

Django/basic_tv/mysite/templates/mysite/lunch.html
{% extends 'base.html' %}

{% block style %}
<style>
  div {
    color: blue;
  }
</style>
{% endblock style %}


{% block content %}
<div>
  <h1>Happy Lunch!</h1>
  <h2>오늘의 점심 {{ menu }}!!</h2>
</div>
{% endblock content %}

Django/basic_tv/pages/templates/b/dinner.html
{% extends 'mysite/base.html' %}

  <h1>Dinner!</h1>
  <h2>저녁 먹을 사람! {{ count }}</h2>
  <h2>저녁 메뉴! {{ menu }} </h2>

Django/basic_tv/pages/templates/b/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>This is PAGES/HOME</h1>
</body>
</html>

Django/basic_tv/templates/_footer.html
<footer>
  copyright 2022 ssafy 7ss5
</footer>

Django/basic_tv/templates/_nav.html
<nav>
  <ul>
    <li><a href="{% url 'mysite:lunch' %}">lunch</a></li>
    <li><a href="{% url 'mysite:lotto' %}">lotto</a></li>
    <li><a href="{% url 'galaxy:ping' %}">ping</a></li>
    <li><a href="{% url 'galaxy:pingpong' %}">pingpong</a></li>
  </ul>
</nav>

Django/basic_tv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% block style %}{% endblock style %}
</head>
<body>
  
  {% include '_nav.html' %}

  {% block content %}{% endblock %}

  {% include '_footer.html' %}

</body>
</html>