Django/model/model/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('practice.urls')),
]

Django/model/practice/urls.py
from django.urls import path
from . import views

app_name = 'practice'

# /articles/ 
urlpatterns = [
    # /articles/ => article list (전체 목록)
    path('', views.article_list, name='article_list'),
    # /articles/1/ => 해당 pk값을 갖는 article detail
    path('<int:article_pk>/', views.article_detail, name='article_detail'),
]

Django/model/practice/models.py
from django.db import models


# models.Model을 상속받은 경우,
# 클래스는, objects 라는 Manager를 두게 됨
# 인스턴스는, 바로 실행가능한 메서드(.save())가 존재
# 클래스 == 테이블 / 인스턴스 == 레코드

class Student(models.Model):
    # 컬럼(필드)
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    major = models.CharField(max_length=100)
    is_married = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.pk}) {self.name}'


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk}: {self.title}'


"""
Table 생성/수정 반영
1. model class 작성(수정) => 무조건 2번으로
2. $ python manage.py makemigrations [app_name]
3. $ python manage.py migrate [app_name]

Data CRUD

Create(생성)
s1 = Student()
s1.name = 'a'
s1.age = 123
s1.major = 'CS'
s1.save()  # <= db에 반영


Read(조회)
1. 전체 목록
Stduent.objects.all()  # return queryset 

2. 단일 조회
Student.objects.get(pk=1) # return object


Update(수정)
s = Student.objects.get(pk=4)
s.name = '김싸피'
s.is_married = True
s.save()


Delete(삭제)
s = Student.objects.get(pk=4)
s.delete()
"""

Django/model/practice/views.py
from django.shortcuts import render
from .models import Article


def article_list(request):
    # DB의 모든 Article 목록 조회
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }
    return render(request, 'practice/article_list.html', context)


def article_detail(request, article_pk):
    # DB의 pk=article_pk 인 Article 조회
    article = Article.objects.get(pk=article_pk)

    context = {
        'article': article,
    }
    return render(request, 'practice/article_detail.html', context)

Django/model/practice/templates/practice/article_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ article.title }}</h1>

<small>
  {{ article.created_at }} | {{ article.updated_at }}
</small>

<p>{{ article.content }}</p>

{% endblock content %}

Django/model/practice/templates/practice/article_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Article List</h1>

<ul>
  {% for article in articles %}
  {% comment %} <li>
    <a href="/articles/{{ article.pk }}/">{{ article.title }}</a>
  </li> {% endcomment %}

  <li>
    <a href="{% url 'practice:article_detail' article.pk  %}">{{ article.title }}</a>
  </li>
  {% endfor %}
</ul>

{% endblock content %}

Django/model/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}{% endblock content %}
</body>
</html>